# Generated by Django 3.2.9 on 2021-12-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_status',
            field=models.CharField(choices=[('All_of_good', 'All_of_good'), ('Return', 'Return'), ('Cancel', 'Cancel')], default='All_of_good', max_length=20, null=True),
        ),
    ]
