# Generated by Django 3.2.9 on 2021-12-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0006_couponmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponmodel',
            name='based_things',
            field=models.ManyToManyField(to='products.SubcategoryModel', verbose_name='Coupon based these things'),
        ),
    ]
