# Generated by Django 3.2.9 on 2021-12-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_couponmodel_based_things'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponmodel',
            name='code',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
